import ProductSlider from "@components/Sliders/ProductSlider";

export default function Recommendation() {
    const products = [
        {
            id: 1,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt.",
            rating: 4.5,
            numReviews: 100,
            offPercentage: 20,
            originalPrice: "$100",
            newPrice: "$80",
            deliveryCharges: "Free delivery",
        },
        {
            id: 2,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt.",
            rating: 3.5,
            numReviews: 50,
            offPercentage: 10,
            originalPrice: "$50",
            newPrice: "$45",
            deliveryCharges: "$5 delivery",
        },
        {
            id: 3,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 3",
            rating: 4,
            numReviews: 75,
            offPercentage: 30,
            originalPrice: "$80",
            newPrice: "$56",
            deliveryCharges: "Free delivery",
        },
        {
            id: 4,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 4",
            rating: 5,
            numReviews: 120,
            offPercentage: 15,
            originalPrice: "$90",
            newPrice: "$76",
            deliveryCharges: "$5 delivery",
        },
        {
            id: 5,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 5",
            rating: 4.5,
            numReviews: 90,
            offPercentage: 25,
            originalPrice: "$120",
            newPrice: "$90",
            deliveryCharges: "Free delivery",
        },
        {
            id: 6,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 1",
            rating: 4.5,
            numReviews: 100,
            offPercentage: 20,
            originalPrice: "$100",
            newPrice: "$80",
            deliveryCharges: "Free delivery",
        },
        {
            id: 7,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 2",
            rating: 3.5,
            numReviews: 50,
            offPercentage: 10,
            originalPrice: "$50",
            newPrice: "$45",
            deliveryCharges: "$5 delivery",
        },
        {
            id: 8,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 3",
            rating: 4,
            numReviews: 75,
            offPercentage: 30,
            originalPrice: "$80",
            newPrice: "$56",
            deliveryCharges: "Free delivery",
        },
        {
            id: 9,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 4",
            rating: 5,
            numReviews: 120,
            offPercentage: 15,
            originalPrice: "$90",
            newPrice: "$76",
            deliveryCharges: "$5 delivery",
        },
        {
            id: 10,
            imageSrc: "https://via.placeholder.com/300x300",
            name: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod temp eiusmod tempor incididunt. 5",
            rating: 4.5,
            numReviews: 90,
            offPercentage: 25,
            originalPrice: "$120",
            newPrice: "$90",
            deliveryCharges: "Free delivery",
        },
    ];
    return (
        <div className="recommendation-container">
            <ProductSlider products={products} />
        </div>
    );
}
