[www]
slowlog = /var/log/nginx/error.log
expose_php = Off
error_reporting = E_ALL & ~E_NOTICE
display_errors = 1
upload_max_filesize = 50M
post_max_size = 50M
memory_limit = 512M
max_input_time = 3m 
# request_terminate_timeout = 3m

